### ISSUE TITLE
Request: Suppress temperature devices

### ISSUE THREAD

**Issue by mariusstrom** [muelmx/homebridge-decent-advanced-rest-api#1]
I'd love to be able to suppress the temperature devices from being exposed to Homekit. It messes with my automation that uses climate devices in the Kitchen :)

**Comment by muelmx** [comment]
Sounds like a good idea! I’ll tackle it in the near future.

**Comment by muelmx** [comment]
[Beta version](https://www.npmjs.com/package/homebridge-decent-advanced-rest-api/v/1.1.0-beta.0) published :)
@mariusstrom you can give it a try using install alternate version 1.1.0-beta.0 from the home bridge UI.

<img width="1025" alt="image" src="https://user-images.githubusercontent.com/11611674/204825359-927f7b71-de84-4d9e-aa73-b2045c0df584.png">

**Comment by mariusstrom** [comment]
4 minutes of testing and it seems to be working great!

**Comment by mariusstrom** [comment]
(leaving the issue open if you want to close it when you merge it with the main branch)
